-- completed mig_043
-- Converted from: 2023_07_27_182013_smtp_discord_schemaless_to_normal.php

-- ALTER TABLE teams
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;

-- ALTER TABLE teams
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;

-- ALTER TABLE instance_settings
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;

-- ALTER TABLE instance_settings
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;

-- ALTER TABLE teams
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;

-- ALTER TABLE teams
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;

-- ALTER TABLE instance_settings
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;

-- ALTER TABLE instance_settings
-- Review 2023_07_27_182013_smtp_discord_schemaless_to_normal.php for specific alterations
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption VARCHAR(255);
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout INTEGER;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_webhook_url TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_test TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_deployments TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS discord_notifications_status_changes TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_enabled TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_address TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_from_name TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_recipients TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_host TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_port TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_encryption TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_username TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_password TEXT;
ALTER TABLE instance_settings ADD COLUMN IF NOT EXISTS smtp_timeout TEXT;
