services:
  masterdeploy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masterdeploy-engine
    ports:
      - "8000:8000"
      - "5173:5173"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - PORT=8000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
