services:
  postgres:
    image: postgres:16-alpine
    container_name: masterdeploy-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: masterdeploy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masterdeploy-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:9000"
    volumes:
      - ./migrations:/app/migrations
      - ./ui:/app/ui
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/masterdeploy
      APP_ENV: local
      RUST_LOG: info
      UI_DIST_PATH: /app/ui/dist


  frontend:
    image: node:20-alpine
    container_name: masterdeploy-frontend
    working_dir: /app/ui
    restart: always
    volumes:
      - ./ui:/app/ui
      - /app/ui/node_modules # node_modules-un yerli diskdən əzilməməsi üçün anonim volume
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"


volumes:
  pgdata:

