// completed file_0864
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, sqlx::FromRow, Serialize, Deserialize)]
pub struct StandaloneMariadb {
    pub id: uuid::Uuid,
    pub name: Option<String>,
    pub description: Option<String>,
    pub mariadb_root_password: Option<String>,
    pub mariadb_user: Option<String>,
    pub mariadb_password: Option<String>,
    pub mariadb_database: Option<String>,
    pub mariadb_conf: Option<String>,
    pub status: Option<String>,
    pub image: Option<String>,
    pub is_public: Option<String>,
    pub public_port: Option<String>,
    pub ports_mappings: Option<String>,
    pub limits_memory: Option<String>,
    pub limits_memory_swap: Option<String>,
    pub limits_memory_swappiness: Option<String>,
    pub limits_memory_reservation: Option<String>,
    pub limits_cpus: Option<String>,
    pub limits_cpuset: Option<String>,
    pub limits_cpu_shares: Option<String>,
    pub started_at: Option<String>,
    pub restart_count: i32,
    pub last_restart_at: Option<chrono::DateTime<chrono::Utc>>,
    pub last_restart_type: Option<String>,
    pub last_online_at: Option<String>,
    pub public_port_timeout: i32,
    pub enable_ssl: Option<String>,
    pub is_log_drain_enabled: Option<String>,
    pub custom_docker_run_options: Option<String>,
    pub destination_type: Option<String>,
    pub destination_id: Option<uuid::Uuid>,
    pub environment_id: Option<uuid::Uuid>,
    pub health_check_enabled: bool,
    pub health_check_interval: i32,
    pub health_check_timeout: i32,
    pub health_check_retries: i32,
    pub health_check_start_period: i32,
}
