-- completed mig_020
-- Converted from: 2023_03_27_081716_create_applications_table.php

CREATE TABLE IF NOT EXISTS applications (
    repository_project_id INTEGER,
    uuid VARCHAR(255),
    name VARCHAR(255),
    fqdn VARCHAR(255),
    config_hash VARCHAR(255),
    git_repository VARCHAR(255),
    git_branch VARCHAR(255),
    git_commit_sha VARCHAR(255),
    git_full_url VARCHAR(255),
    docker_registry_image_name VARCHAR(255),
    docker_registry_image_tag VARCHAR(255),
    build_pack VARCHAR(255),
    static_image VARCHAR(255),
    install_command VARCHAR(255),
    build_command VARCHAR(255),
    start_command VARCHAR(255),
    ports_exposes VARCHAR(255),
    ports_mappings VARCHAR(255),
    base_directory VARCHAR(255),
    publish_directory VARCHAR(255),
    health_check_path VARCHAR(255),
    health_check_port VARCHAR(255),
    health_check_host VARCHAR(255),
    health_check_method VARCHAR(255),
    health_check_return_code INTEGER,
    health_check_scheme VARCHAR(255),
    health_check_response_text VARCHAR(255),
    health_check_interval INTEGER,
    health_check_timeout INTEGER,
    health_check_retries INTEGER,
    health_check_start_period INTEGER,
    limits_memory VARCHAR(255),
    limits_memory_swap VARCHAR(255),
    limits_memory_swappiness INTEGER,
    limits_memory_reservation VARCHAR(255),
    limits_cpus VARCHAR(255),
    limits_cpuset VARCHAR(255),
    limits_cpu_shares INTEGER,
    status VARCHAR(255),
    preview_url_template VARCHAR(255),
    destination TEXT,
    source TEXT,
    private_key_id BIGINT,
    environment_id BIGINT
);

DROP TABLE IF EXISTS applications;
