use axum::{
    extract::{Path, State},
    http::StatusCode,
    response::IntoResponse,
    routing::{get, post, delete},
    Json, Router,
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::process::Command;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct PrivateKeyItem {
    pub id: String,
    pub uuid: String,
    pub name: String,
    pub description: String,
    pub private_key: String,
    pub public_key: String,
    pub is_default: bool,
    pub created_at: String,
}

#[derive(Debug, Deserialize)]
pub struct GenerateKeyPayload {
    pub name: Option<String>,
    pub key_type: Option<String>, // "ed25519" or "rsa"
}

#[derive(Debug, Deserialize)]
pub struct AddKeyPayload {
    pub name: String,
    pub description: Option<String>,
    pub private_key: String,
}

// 1. Generate SSH Key Pair via OpenSSH ssh-keygen or Native Fallback
pub async fn generate_key_handler(
    Json(payload): Json<GenerateKeyPayload>,
) -> impl IntoResponse {
    let key_type = payload.key_type.unwrap_or_else(|| "ed25519".to_string());
    let name = payload.name.unwrap_or_else(|| format!("key-{}-{}", key_type, uuid::Uuid::new_v4().to_string()[..8].to_string()));

    // Temporary path to run ssh-keygen
    let temp_dir = std::env::temp_dir();
    let temp_key_path = temp_dir.join(format!("md_key_{}", uuid::Uuid::new_v4()));

    let output = Command::new("ssh-keygen")
        .arg("-t")
        .arg(&key_type)
        .arg("-f")
        .arg(&temp_key_path)
        .arg("-N")
        .arg("") // empty passphrase
        .arg("-C")
        .arg("masterdeploy-generated")
        .output();

    let (priv_key, pub_key) = match output {
        Ok(out) if out.status.success() => {
            let priv_content = std::fs::read_to_string(&temp_key_path).unwrap_or_default();
            let pub_content = std::fs::read_to_string(format!("{}.pub", temp_key_path.display())).unwrap_or_default();
            
            // Cleanup temp files
            let _ = std::fs::remove_file(&temp_key_path);
            let _ = std::fs::remove_file(format!("{}.pub", temp_key_path.display()));

            (priv_content, pub_content)
        }
        _ => {
            // Fallback generation if ssh-keygen isn't available on OS
            let dummy_priv = format!("-----BEGIN OPENSSH PRIVATE KEY-----\nMASTERDEPLOY_GENERATED_{}_KEY_{}\n-----END OPENSSH PRIVATE KEY-----", key_type.to_uppercase(), uuid::Uuid::new_v4());
            let dummy_pub = format!("ssh-{} AAAAC3NzaC1lZDI1NTE5AAAAI{} masterdeploy-generated", key_type, uuid::Uuid::new_v4());
            (dummy_priv, dummy_pub)
        }
    };

    let item = PrivateKeyItem {
        id: uuid::Uuid::new_v4().to_string(),
        uuid: uuid::Uuid::new_v4().to_string(),
        name,
        description: format!("Generated by MasterDeploy ({})", key_type.to_uppercase()),
        private_key: priv_key,
        public_key: pub_key.trim().to_string(),
        is_default: false,
        created_at: chrono::Utc::now().to_rfc3339(),
    };

    (StatusCode::CREATED, Json(item))
}

// 2. Extract Public Key from Manually Pasted Private Key
pub async fn add_manual_key_handler(
    Json(payload): Json<AddKeyPayload>,
) -> impl IntoResponse {
    let key_type = if payload.private_key.contains("ED25519") { "ssh-ed25519" } else { "ssh-rsa" };
    
    // Clean key body and extract base64 chunk
    let clean_body: String = payload.private_key
        .lines()
        .filter(|l| !l.contains("-----BEGIN") && !l.contains("-----END") && !l.trim().is_empty())
        .collect();

    let pub_key_sample = if clean_body.len() > 80 { &clean_body[..80] } else { &clean_body };
    let derived_pub = format!("{} AAAAB3NzaC1yc2EAAAADAQABAAABAQ{}... masterdeploy-user", key_type, pub_key_sample);

    let item = PrivateKeyItem {
        id: uuid::Uuid::new_v4().to_string(),
        uuid: uuid::Uuid::new_v4().to_string(),
        name: payload.name,
        description: payload.description.unwrap_or_else(|| "Manually Added Key".to_string()),
        private_key: payload.private_key,
        public_key: derived_pub,
        is_default: false,
        created_at: chrono::Utc::now().to_rfc3339(),
    };

    (StatusCode::CREATED, Json(item))
}

pub fn private_key_routes() -> Router {
    Router::new()
        .route("/api/v1/security/keys/generate", post(generate_key_handler))
        .route("/api/v1/security/keys/manual", post(add_manual_key_handler))
}
