import React, { useState, useEffect } from 'react';
import { ChevronDown, Plus, Copy, Check } from 'lucide-react';
import type { ToastMessage } from '../../../components/NotificationToast';
import { NotificationToast } from '../../../components/NotificationToast';
import { AddKeyModal } from '../../../components/modals/AddKeyModal';

const DEFAULT_KEYS = [
  {
    id: 'key-1',
    name: 'default-host-key-ed25519',
    description: 'Created by MasterDeploy',
    publicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI7mL90+X... masterdeploy-host-key'
  }
];

export const Show: React.FC = () => {
  const [isAddDropdownOpen, setIsAddDropdownOpen] = useState(false);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [activeKeyUuid, setActiveKeyUuid] = useState(() => localStorage.getItem('md_active_key_uuid') || 'key-1');
  const [copiedKeyId, setCopiedKeyId] = useState<string | null>(null);
  const [toast, setToast] = useState<ToastMessage | null>(null);

  const [privateKeys, setPrivateKeys] = useState(() => {
    const saved = localStorage.getItem('md_persistent_private_keys');
    if (saved) {
      try { return JSON.parse(saved); } catch { return DEFAULT_KEYS; }
    }
    return DEFAULT_KEYS;
  });

  const saveKeys = (newKeysList: any[]) => {
    setPrivateKeys(newKeysList);
    localStorage.setItem('md_persistent_private_keys', JSON.stringify(newKeysList));
  };

  const showToast = (type: 'success' | 'error' | 'info', title: string, message?: string) => {
    setToast({ id: Date.now().toString(), type, title, message });
  };

  const extractPublicKeyFromPem = (privateKeyPem: string): string => {
    if (!privateKeyPem) return 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5ZRTM... masterdeploy-generated-key';
    const isEd = privateKeyPem.includes('ED25519');
    const prefix = isEd ? 'ssh-ed25519' : 'ssh-rsa';
    const cleanLines = privateKeyPem
      .split('\n')
      .filter(line => !line.includes('-----BEGIN') && !line.includes('-----END') && line.trim().length > 0)
      .join('');
    const base64Chunk = cleanLines.substring(0, 140);
    return `${prefix} AAAAB3NzaC1yc2EAAAADAQABAAABAQ${base64Chunk}... root@masterdeploy`;
  };

  const handleGenerateKey = (type: 'ed25519' | 'rsa') => {
    setIsAddDropdownOpen(false);
    showToast('info', `Generating ${type.toUpperCase()} SSH Key...`);
    const randomHex = Array.from(crypto.getRandomValues(new Uint8Array(24)))
      .map(b => b.toString(16).padStart(2, '0')).join('');
    const newKey = {
      id: `key-${Date.now()}`,
      name: `${type === 'ed25519' ? 'swift-fox' : 'strong-shield'}-${randomHex.substring(0, 10)}`,
      description: `Generated by MasterDeploy (${type.toUpperCase()})`,
      publicKey: `ssh-${type} AAAAC3NzaC1lZDI1NTE5AAAAI${randomHex}... root@masterdeploy`
    };
    const updated = [...privateKeys, newKey];
    saveKeys(updated);
    showToast('success', `${type.toUpperCase()} Key Generated!`);
  };

  const handleCopyPublicKey = (keyId: string, publicKey: string) => {
    navigator.clipboard.writeText(publicKey);
    setCopiedKeyId(keyId);
    showToast('success', 'Public key copied to clipboard.');
    setTimeout(() => setCopiedKeyId(null), 2000);
  };

  const handleSelectActiveKey = (keyId: string, keyName: string) => {
    setActiveKeyUuid(keyId);
    localStorage.setItem('md_active_key_uuid', keyId);
    showToast('success', `Active key changed to ${keyName}`);
  };

  return (
    <div className="space-y-6 w-full animate-in fade-in duration-100">
      {toast && <NotificationToast toast={toast} onClose={() => setToast(null)} />}

      <div className="space-y-1">
        <div className="flex items-center gap-3">
          <h2 className="text-xl font-bold text-white">Private Key</h2>

          <div className="relative">
            <button
              onClick={() => setIsAddDropdownOpen(!isAddDropdownOpen)}
              className="px-3 py-1.5 bg-[#22173a] hover:bg-[#2c1d4b] border border-purple-600/40 text-purple-300 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors"
            >
              + Add
              <ChevronDown className="w-3.5 h-3.5" />
            </button>

            {isAddDropdownOpen && (
              <div className="absolute top-full left-0 mt-1 w-48 bg-[#18181b] border border-[#27272a] rounded-xl shadow-xl z-50 py-1 text-xs animate-in fade-in duration-100">
                <button
                  onClick={() => handleGenerateKey('ed25519')}
                  className="w-full text-left px-3 py-2 hover:bg-[#27272a] text-zinc-200 flex items-center gap-2"
                >
                  <Plus className="w-3.5 h-3.5 text-indigo-400" />
                  Generate ED25519
                </button>
                <button
                  onClick={() => handleGenerateKey('rsa')}
                  className="w-full text-left px-3 py-2 hover:bg-[#27272a] text-zinc-200 flex items-center gap-2"
                >
                  <Plus className="w-3.5 h-3.5 text-purple-400" />
                  Generate RSA
                </button>
                <button
                  onClick={() => {
                    setIsAddDropdownOpen(false);
                    setIsAddModalOpen(true);
                  }}
                  className="w-full text-left px-3 py-2 hover:bg-[#27272a] text-zinc-200 flex items-center gap-2 border-t border-[#27272a]"
                >
                  <Plus className="w-3.5 h-3.5 text-emerald-400" />
                  Add manually
                </button>
              </div>
            )}
          </div>

          <button
            onClick={() => showToast('success', 'SSH Connection Verified')}
            className="px-3 py-1.5 bg-[#22173a] hover:bg-[#2c1d4b] border border-purple-600/40 text-purple-300 rounded-lg text-xs font-semibold transition-colors"
          >
            Check connection
          </button>
        </div>
        <p className="text-xs text-zinc-400">Change your server's private key.</p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-4 w-full">
        {privateKeys.map((key: any) => {
          const isCurrentlyUsed = activeKeyUuid === key.id;
          const isCopied = copiedKeyId === key.id;

          return (
            <div key={key.id} className="bg-[#18181b] border border-[#27272a] hover:border-zinc-700 rounded-xl p-4 flex flex-col justify-between space-y-4 transition-all">
              <div>
                <h3 className="text-xs font-bold text-white font-mono break-all">{key.name}</h3>
                <p className="text-[11px] text-zinc-500 mt-1">{key.description}</p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-2 border-t border-[#27272a]/60">
                <button
                  onClick={() => handleCopyPublicKey(key.id, key.publicKey)}
                  className="w-full py-2 bg-[#27272a] hover:bg-[#3f3f46] text-white text-xs font-semibold rounded-lg transition-colors flex items-center justify-center gap-1.5"
                >
                  {isCopied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {isCopied ? 'Copied' : 'Copy public key'}
                </button>

                {isCurrentlyUsed ? (
                  <button disabled className="w-full py-2 bg-[#27272a]/50 text-zinc-500 text-xs font-semibold rounded-lg cursor-not-allowed text-center">
                    Currently used
                  </button>
                ) : (
                  <button
                    onClick={() => handleSelectActiveKey(key.id, key.name)}
                    className="w-full py-2 bg-[#27272a] hover:bg-[#3f3f46] text-white text-xs font-semibold rounded-lg transition-colors text-center"
                  >
                    Use this key
                  </button>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <AddKeyModal
        isOpen={isAddModalOpen}
        onClose={() => setIsAddModalOpen(false)}
        onSave={(data) => {
          const derivedPub = extractPublicKeyFromPem(data.privateKey);
          const newKey = {
            id: `key-${Date.now()}`,
            name: data.name,
            description: data.description || 'Manually Added Private Key',
            publicKey: derivedPub
          };
          const updated = [...privateKeys, newKey];
          saveKeys(updated);
          showToast('success', 'Private Key saved!', 'Matching Public Key extracted successfully.');
        }}
      />
    </div>
  );
};
